---
sidebar: sidebar 
permalink: learn-about-sustainability.html 
keywords: activeiq, sustainability, sustainability score, sustainability dashboard, bluexp, benefits, ONTAP, NetApp Console 
summary: Fornece informações sobre sustentabilidade que permitem reduzir o consumo de energia e permite que você trabalhe em direção aos seus objetivos ambientais. 
---
= Saiba mais sobre sustentabilidade
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A sustentabilidade permite que você reduza o consumo de energia e trabalhe para atingir seus objetivos ambientais.  Isso permite que você alinhe seus sistemas de armazenamento com práticas ecológicas e alcance as metas de sustentabilidade.

Você pode visualizar a pontuação de sustentabilidade e o uso projetado de energia, carbono direto e calor no painel de Sustentabilidade.  Você pode ajustar a porcentagem de mitigação de carbono para locais específicos.  Você também pode visualizar a pontuação de sustentabilidade no nível do cluster.  Com base na pontuação de sustentabilidade, você pode avaliar a postura de sustentabilidade e implementar as ações recomendadas pela NetApp para melhorar a pontuação.  Para saber mais sobre o painel de Sustentabilidade, acesselink:sustainability-dashboard-overview.html["Visão geral do painel de sustentabilidade"] .


NOTE: A sustentabilidade é compatível com sistemas Cloud Volumes ONTAP, AFF (A-Series e C-Series), e-Series, FAS e StorageGRID.

Você pode ver o vídeo a seguir para entender o painel Sustentabilidade:

video::yNRHeOvbGX8[youtube,width=848,height=480]


== Benefícios da sustentabilidade

A sustentabilidade oferece os seguintes benefícios:

* Acelere o desempenho reduzindo o número de dispositivos de armazenamento para armazenar a mesma quantidade de dados.
* Reduzir os custos de storage otimizando a utilização dos sistemas de storage.
* Reduzir as pegadas de carbono usando energia renovável em data centers.
* Melhorar a eficiência energética através da implementação de políticas energeticamente eficientes.

