---
settings:
  name: Digital Advisor
  release_notes_autogen:
    release_notes_repo: console-relnotes
  harmony_integration: maestro
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: pt-br,us-en,de-de,es-es,fr-fr,it-it,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos do Digital Advisor
    url: "/index.html"
  - title: Notas de lançamento
    entries:
    - title: O que há de novo
      url: "/reference_new_activeiq.html"
    - title: Limitações conhecidas
      url: "/reference_limitations_activeiq.html"
  - title: Comece agora
    entries:
    - title: Início rápido para o Digital Advisor
      url: "/concept_getting_started_2.html"
    - title: Saiba mais sobre os recursos do Digital Advisor
      url: "/concept_understand_activeiq_features.html"
    - title: Acesse o Digital Advisor no NetApp Console
      url: "/digital-advisor-integration-with-console.html"
    - title: Saiba mais sobre o Digital Advisor
      url: "/concept_key_terms.html"
    - title: Saiba mais sobre o AutoSupport
      url: "/concept_autosupport.html"
    - title: Inicie sessão no Digital Advisor
      url: "/task_login_activeiq.html"
    - title: Provisione watchlist
      entries:
      - title: Saiba mais sobre listas de vigilância
        url: "/concept_overview_dashboard.html"
      - title: Crie uma lista de observação
        url: "/task_add_watchlist.html"
      - title: Gerenciar uma lista de observação
        url: "/task_manage_watchlists.html"
    - title: Perguntas frequentes para o Digital Advisor
      url: reference_aiq_faq.html
  - title: Use o Digital Advisor
    entries:
    - title: Analise atributos de bem-estar
      entries:
      - title: Saiba mais sobre o widget de bem-estar
        url: "/concept_overview_wellness.html"
      - title: Identifique os riscos do sistema de armazenamento e tome medidas corretivas.
        url: "/task_view_risk_and_take_action.html"
      - title: Detectar riscos de segurança e tomar medidas corretivas.
        url: "/task_increase_protection_against_hackers_and_Ransomware_attacks.html"
      - title: Proteja seus sistemas de armazenamento contra riscos de ransomware.
        url: "/task_protect_systems_against_ransomware_risks.html"
      - title: Analise os atributos de bem-estar e reconheça os riscos.
        url: "/task_view_and_acknowledge_risks.html"
      - title: Visualizar histórico de riscos do sistema de armazenamento
        url: "/task_view_wellness_history.html"
      - title: Visualize e mitigue riscos usando o Unified Manager ou o Ansible Playbook.
        url: "/task_view_risks_remediated_unified_manager.html"
      - title: Utilize o Digital Advisor para corrigir os riscos críticos identificados.
        url: "/task_avoid_the_downtime_and_possible_data_loss.html"
      - title: Inscreva-se para receber notificações sobre a integridade do sistema
          de armazenamento.
        url: "/task_subscribe_to_wellness_review_email.html"
      - title: Identificar as renovações de software e hardware para o sistema de
          armazenamento.
        url: "/task_renew_software_and_hardware.html"
      - title: Visualize o estado de saúde dos clusters e nós usando o widget ClusterViewer.
        url: "/task_analyze_wellness_clusters_and_nodes.html"
    - title: Analisar a sustentabilidade do sistema de armazenamento
      entries:
      - title: Saiba mais sobre sustentabilidade
        url: "/learn-about-sustainability.html"
      - title: Acesse o painel de Sustentabilidade
        url: "/get_started_sustainability_dashboard.html"
      - title: Saiba mais sobre os recursos do painel de Sustentabilidade
        url: "/sustainability-dashboard-overview.html"
      - title: Melhorar a pontuação de sustentabilidade do sistema de armazenamento
        url: "/improve_sustainability_score.html"
    - title: Gerar um plano de atualização
      entries:
      - title: Saiba mais sobre como gerar um plano de atualização do ONTAP.
        url: "/upgrade_advisor_overview.html"
      - title: Gere um plano de atualização do ONTAP para clusters únicos e múltiplos.
        url: "/generate_upgrade_plan_single_multiple_clusters.html"
      - title: Ver recomendações de atualização de firmware
        url: "/view-firmware-update-recommendations.html"
    - title: Ver detalhes do sistema
      entries:
      - title: Veja os detalhes do inventário do sistema de armazenamento.
        url: "/task_view_inventory_details.html"
      - title: Visualize os dados de máquinas virtuais disponíveis no Data Infrastructure
          Insights.
        url: "/task-integrating-with-cloud-insights-to-view-vm-details.html"
      - title: Visualize casos de suporte e detalhes do sistema de armazenamento com
          o widget Valuable Insights.
        url: "/task_view_valuable_insight_widget.html"
      - title: Visualizar a utilização de capacidade com a subscrição do NetApp Keystone
        url: "/view_keystone_capacity_utilization.html"
    - title: Identifique os requisitos do sistema de forma proativa
      entries:
      - title: Gerencie os requisitos de capacidade do sistema de armazenamento com
          o widget de Planejamento.
        url: "/concept_overview_planning.html"
      - title: Identificar sistemas de armazenamento próximos do limite de capacidade
        url: "/task_identify_capacity_system.html"
      - title: Gerenciar limites de capacidade de armazenamento de volume
        url: "/task_avoid_a_volume_filling_up_to_prevent_an_outage.html"
      - title: Determine se uma atualização tecnológica é recomendada para o sistema
          de armazenamento.
        url: "/evaluate-tech-refresh.html"
      - title: Renovar o software e o hardware do sistema de armazenamento
        url: "/task_renew_software_and_hardware.html"
    - title: Analise a integridade do sistema de armazenamento com recomendações de
        nuvem.
      url: "/task-informed-decisions-based-on-cloud-recommendations.html"
    - title: Identifique o desvio de configuração
      entries:
      - title: Detectar desvios de configuração no sistema de armazenamento
        url: "/concept_overview_config_drift.html"
      - title: Adicionar um modelo de deriva de configuração para o sistema de armazenamento
        url: "/task_add_config_drift_template.html"
      - title: Comparar modelos de deriva de configuração
        url: "/task_compare_config_drift_template.html"
      - title: Gere um relatório de linha do tempo de desvio de configuração
        url: "/task_generate_drift_timeline_report.html"
      - title: Gerenciar modelos de deriva de configuração
        url: "/task_manage_template.html"
    - title: Melhorar a eficiência e o desempenho do sistema de armazenamento.
      entries:
      - title: Veja as economias em termos de capacidade e eficiência de armazenamento.
        url: "/task_analyze_storage_efficiency.html"
      - title: Visualizar gráficos de desempenho do sistema de armazenamento
        url: "/task_view_performance_graphs.html"
    - title: Analise a saúde do sistema de armazenamento.
      entries:
      - title: Saiba mais sobre o painel de verificação de saúde.
        url: "/concept_understand_health_check_dashboard.html"
      - title: Comece a usar o painel de verificação de integridade
        url: "/concept_get_started_with_health_check_dashboard.html"
      - title: Renovar contratos de suporte
        url: "/task_renew_support_contracts_for_your_systems.html"
    - title: Atualize para otimizar sua base de instalação
      entries:
      - title: Oferta de suporte para atualização
        url: "/task_upgrade_support_offering.html"
      - title: Atualize o firmware AFF e FAS usando o Ansible Playbook.
        entries:
        - title: Baixe o pacote Ansible de firmware AFF e FAS .
          url: "/task_update_AFF_FAS_firmware.html"
        - title: Atualize o firmware AFF e FAS usando um pacote Ansible (para usuários
            experientes).
          url: "/task_install_execute_firmware_update_exp_user.html"
        - title: Instalar e executar o pacote de automação do AFF e do FAS firmware
            (iniciantes)
          entries:
          - title: Hospede os arquivos de firmware AFF e FAS em um servidor web.
            url: "/task_hosting_firmware_files_using_web_server.html"
          - title: Atualize o arquivo de inventário para a atualização de firmware
              AFF e FAS .
            url: "/concept_working_with_inventory_file.html"
          - title: Execute o playbook do Ansible usando a imagem Docker da NetApp.
            url: "/task_execute_ansible_playbook_using_docker.html"
          - title: Execute o playbook do Ansible sem a imagem Docker da NetApp.
            url: "/task_execute_ansible_playbook_without_docker.html"
          - title: Valide a instalação do firmware AFF e FAS no sistema de armazenamento.
            url: "/task_validate_firmware_installation.html"
    - title: Integre dados usando APIs
      entries:
      - title: Saiba mais sobre os serviços da API do Digital Advisor.
        url: "/concept_overview_API_service.html"
      - title: Gere tokens para usar os serviços da API do Digital Advisor.
        url: "/task_generate_tokens_API_services.html"
      - title: Utilize o catálogo de APIs do Digital Advisor para executar as APIs.
        url: "/task_view_API_catalog.html"
    - title: Gerar relatórios personalizados
      entries:
      - title: Saiba mais sobre os relatórios do Digital Advisor.
        url: "/concept_report_types.html"
      - title: Gerar ou agendar um relatório
        url: "/task_generate_reports.html"
  - title: Conhecimento e apoio
    entries:
    - title: Registre-se para obter suporte
      url: "/reference_ansible_troubleshoot_feedback_support.html"
    - title: Obtenha ajuda
      url: "/concept_get_more_information.html"
  - title: Avisos legais
    url: "/legal-notices.html"
product-family:
  name: NetApp Console
  repo: console-family
