---
sidebar: sidebar 
permalink: task_protect_systems_against_ransomware_risks.html 
keywords: ransomware, risks, ransomware risks 
summary:  
---
= Proteja os sistemas de armazenamento gerenciados pela Digital Advisor contra riscos de ransomware.
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ao fazer login no Digital Advisor, você pode exibir as *ações* destacadas no widget *Defesa de Segurança e ransomware*, que mostra a contagem de riscos.

Você pode visualizar os riscos relacionados à criação de snapshots, retenção e FPolicy do ONTAP e, em seguida, tomar medidas para corrigi-los.

.Passos
. Inicie sessão no Digital Advisor.
. Selecione *Ações* no widget *Segurança & Defesa contra Ransomware*.
. Desmarque a caixa de verificação *Vulnerabilidades de segurança*.
. Para os riscos apresentados, verifique o nível de impactos e siga as acões recomendadas.
. Selecione a guia *Riscos Exclusivos* e selecione o link na coluna *Ação Corretiva*.
. Selecione a aba *Sistemas Afetados* para visualizar os sistemas com riscos.
. Selecione as ações corretivas recomendadas para proteger os sistemas.

