---
sidebar: sidebar 
permalink: task_subscribe_to_wellness_review_email.html 
keywords: wellness, wellness review subscription, unsubscribe, supportedge expert, supportedge advisor 
summary:  
---
= Assine as notificações sobre a integridade do sistema de armazenamento do Digital Advisor.
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode se inscrever no boletim informativo por e-mail para receber um resumo mensal do status de desempenho, dos sistemas de armazenamento que estão próximos da data de renovação e dos sistemas de armazenamento que precisam de atualização para os produtos NetApp em sua base instalada. Você receberá um e-mail com uma avaliação de desempenho para que possa visualizar um resumo mensal e tomar as medidas necessárias para otimizar seus sistemas de armazenamento. Você também tem opções para visualizar, editar, compartilhar e excluir suas assinaturas. A qualquer momento, se você decidir que não deseja mais receber e-mails, poderá cancelar a sua inscrição.

Depois que a assinatura estiver ativada, você deverá selecionar uma data de início ao adicionar uma assinatura. O resumo mensal do e-mail fornece uma visão das ações de bem-estar, renovação, atualização e verificação de integridade excecionais. Você pode confirmar o endereço de e-mail e o e-mail é enviado para o endereço de e-mail especificado. Você também tem a opção de excluir assinaturas.


NOTE: Esse recurso está disponível somente por meio das ofertas de serviços do NetApp SupportEdge Advisor e do SupportEdge Expert.

.Passos
. No painel esquerdo, clique em *Revisão de bem-estar*.
. Clique em *Adicionar assinatura*.
. Forneça as informações necessárias nos campos *nomeie a assinatura*, *escolha Categoria*, *pesquisar Cliente* e *Email* na caixa de diálogo *Adicionar nova assinatura*.
. Clique em *Subscribe*.
+
Após a assinatura bem-sucedida, você receberá uma mensagem *assinatura adicionada*.


