---
sidebar: sidebar 
permalink: task_view_and_acknowledge_risks.html 
keywords: wellness, performance, efficiency, availability, capacity, security vulnerabilities, protection, protect, acknowledge, unacknowledge, disregard 
summary: Fornece informações para visualizar e analisar o bem-estar do seu sistema de armazenamento e reconhecer os riscos. 
---
= Analise os atributos de bem-estar no Digital Advisor e reconheça os riscos.
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode analisar os atributos de bem-estar do seu sistema de storage visualizando as ações e os riscos associados a eles. Você deve visualizar as ações corretivas e mitigar manualmente o risco.

.Passos
. Selecione o widget de atributo de bem-estar no painel ou selecione *Ver todas as ações* para visualizar a lista de todas as ações e riscos.
. Veja os *ações* e *riscos* associados ao atributo wellness.
. Selecione *Ações* para visualizar os riscos associados às ações, selecione *Riscos* para visualizar todos os riscos ou selecione *Sistemas Afetados* para visualizar os sistemas que requerem atenção.
. Selecione o risco para visualizar o resumo do risco.
. Selecione *Ack* para confirmar o risco.
+
As informações detalhadas de resumo de risco são fornecidas juntamente com ações corretivas que devem ser executadas manualmente para mitigar o risco.

. Se você não deseja ou não pode mitigar o risco neste momento, forneça os valores para os campos e selecione *Acknowledge*.
+
O risco será acrescentado aos riscos reconhecidos.




NOTE: Se você não quiser mais que um risco seja reconhecido, poderá desconsiderá-lo selecionando *Un-Ack* e seguindo os mesmos passos.
