---
sidebar: sidebar 
permalink: task_identify_capacity_system.html 
keywords: capacity, space, increase, ONTAP systems, StorageGRID 
summary: Fornece informações para aumentar a capacidade do sistema. 
---
= Identifique sistemas de armazenamento próximos do limite de capacidade no Digital Advisor.
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Identifique sistemas que estejam atingindo limites de capacidade proativamente e envie uma solicitação para aumentar a capacidade do seu sistema de storage.

No ONTAP, você pode visualizar sistemas que excederam 90% da capacidade ou excederam 90% da capacidade em 1, 3 e 6 meses. No StorageGRID, você pode visualizar sistemas que excederam 70% da capacidade ou excederam 70% da capacidade em 1, 3 e 6 meses.

.Passos
. No widget *Planning*, clique em *Capacity Additions*.
+
Por padrão, os sistemas ONTAP que excederam 90% de capacidade ou estão próximos a 90% de capacidade são exibidos.

. Clique no separador *StorageGRID* para ver os sistemas StorageGRID que excederam 70% de capacidade ou que estão perto de 70% de capacidade.
. Selecione os sistemas para os quais deseja aumentar a capacidade.
. Clique em *View Capacity Forecast* (Visualizar previsão de capacidade) para visualizar a previsão de capacidade para os próximos 6 meses.
. Clique em *solicitar para adicionar capacidade*.
. Opcionalmente, forneça quaisquer comentários.
. Clique em *Enviar* para enviar a solicitação à equipe de armazenamento do NetApp para auxiliar na adição de capacidade para os sistemas selecionados.

