---
sidebar: sidebar 
permalink: task_view_inventory_details.html 
keywords: inventory, platforms, systems, clusters, sites 
summary: Fornece informações sobre o inventário geral que você possui. 
---
= Consulte os detalhes do inventário do seu sistema de armazenamento no Digital Advisor.
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O widget *Inventário* fornece um resumo do total de sistemas e dos switches de suporte que você possui.  Isso inclui produtos habilitados e não habilitados Digital Advisor .

Você também pode gerar o relatório da lista de observação selecionada e enviar o relatório por e-mail para um máximo de 5 destinatários.

video::ttbpbT5uTBI[youtube,width=848,height=480]


[[view-system-details]]
== Ver detalhes do sistema

.Passos
. No widget *Inventário*, selecione *Sistemas* para visualizar as informações do sistema de todas as plataformas ou selecione o tipo de plataforma e, em seguida, selecione *Sistemas* para visualizar sistemas específicos dessa plataforma.
. Selecione o nó ou o cluster para visualizar informações detalhadas sobre o sistema.
. Selecione *Download* para baixar o relatório de *Inventory* e visualizar os detalhes do sistema em formato .xls.
. Selecione *Download* para baixar o relatório *Ansible Inventory* e visualizar os detalhes do sistema nos formatos .yml e .ini no nível da região ou do site.
+
Os arquivos do Ansible Inventory podem ser usados com arquivos personalizados do Ansible Playbook para fazer alterações na configuração da infraestrutura.





[[view-support-entitled-switch-details]]
== Ver detalhes do switch de suporte

.Passos
. No widget *Inventário*, selecione *Switches com direito a suporte* para visualizar informações sobre todos os switches com direito a suporte.

