---
sidebar: sidebar 
permalink: task_view_performance_graphs.html 
keywords: performance, performance graph, graphs, digital advisor, performance charts, day, week, 1 month, 2 months, calendar, chart data, performance on node level, graph, node level 
summary: Fornece informações sobre o desempenho. 
---
= Visualize os gráficos de desempenho do sistema de armazenamento no Digital Advisor.
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Os gráficos de desempenho permitem analisar o desempenho dos seus dispositivos de armazenamento. Você pode exibir gráficos de desempenho detalhados de um cluster ONTAP ou vários nós de um cluster ONTAP e controladores e-Series. Esses gráficos fornecem dados históricos de desempenho, que podem ser usados para entender a tendência de desempenho e a análise de padrões. Você pode selecionar uma data no calendário para visualizar gráficos de desempenho para um dia, semana, mês, dois meses e doze meses. Você pode selecionar vários nós para exibir um gráfico específico ao mesmo tempo.

Você tem uma opção para definir preferências, por exemplo, você pode exibir um gráfico para três nós ou dois gráficos para três nós.

Ao exibir o gráfico pela primeira vez, a aba de 1 semana é pré-selecionada e apresenta os dados de 1 semana em formato gráfico para facilitar a compreensão de grandes quantidades de dados e da relação entre diferentes séries de dados. Se você quiser redefinir o intervalo de datas, por exemplo, pode selecionar a aba de 1 mês e selecionar as datas no calendário.

Você também tem uma opção para ampliar o gráfico de desempenho; os pontos de dados individuais são exibidos.

video::fWrHYX17xT8[youtube,width=848,height=480]
.Passos
. No painel, selecione *Desempenho*.
+
Para os sistemas ONTAP, você pode selecionar a guia *Nó* para visualizar o desempenho de um único nó de um cluster ONTAP, selecionar a guia *Camada Local* para visualizar o desempenho da camada local ou selecionar a guia *Volume* para visualizar o desempenho do volume. Por padrão, o desempenho do cluster é exibido.

+
Para sistemas e-Series, você pode visualizar os gráficos apenas a um nível de controlador.



. Selecione 1 dia, 1 semana, 1 mês, 2 meses ou 12 meses, no calendário, para visualizar dados de desempenho em um formato gráfico.
+
Por exemplo, selecione a guia 2 meses para exibir dados por 2 meses. Isso permite que você visualize dados específicos por uma duração com base em seus requisitos de desempenho.

. Os gráficos de desempenho a seguir com as métricas necessárias estão disponíveis para clusters e nós do ONTAP:


[cols="25,25,25,25"]
|===
| Para cluster | Para nó | Para nível local | Para volume 


| IOPS | Utilização da CPU - desempenho máximo (espaço livre) | Taxa de transferência média | IOPS 


| Taxa de transferência de rede | Latência | Utilização média | Latência 


|  | IOPS |  |  


|  | Protocolo de IOPS |  |  


|  | Taxa de transferência de rede |  |  
|===
. Os seguintes gráficos de desempenho com as métricas necessárias estão disponíveis para os controladores e-Series:
+
** Utilização de CPU
** Latência
** IOPS
** Taxa de transferência



