---
sidebar: sidebar 
permalink: task_analyze_storage_efficiency.html 
keywords: capacity, storage efficiency, data reduction, savings 
summary: Veja detalhes sobre a capacidade e as economias de eficiência de storage para o seu sistema de storage. 
---
= Visualize as economias de capacidade e eficiência de armazenamento no Digital Advisor.
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode visualizar os detalhes de capacidade e a economia de eficiência de storage do seu sistema e tomar as medidas apropriadas. As informações de capacidade e eficiência de storage podem ser visualizadas no nível do cluster ou no nível de nó.


NOTE: Esse recurso não é suportado em sistemas e-Series.

O painel de controle de capacidade exibe os detalhes de capacidade e a previsão de capacidade do seu sistema. A previsão de capacidade utiliza informações históricas de capacidade para identificar a utilização de cada sistema. Com base nos dados históricos (dados de um ano, se disponíveis) de capacidade utilizada e alocada, o algoritmo considera a utilização atual de cada sistema e gera uma previsão para a utilização do sistema nos próximos 1 a 6 meses.

O painel de eficiência de storage exibe a razão de redução de dados, o espaço lógico utilizado, o espaço físico utilizado e o total de dados economizados. A razão de redução de dados e a economia podem ser visualizadas com e sem cópias de snapshot para sistemas AFF, sistemas não-AFF ou ambos. A economia total de dados em todo o storage do cliente pode ser visualizada por recurso de eficiência, como deduplicação de volume, compressão de volume, compactação, volumes FlexClone e cópias de snapshot. Você pode visualizar os 5 principais sistemas de storage com a melhor razão de eficiência. Você também pode visualizar a eficiência de SAN e NAS sem cópias de snapshot em nível de nó para sistemas ONTAP, incluindo AFF A-Series, AFF C190, All SAN Array e FAS500.

video::8Ge3_0qlyxA[youtube,width=848,height=480]
.Passos
. No painel esquerdo, clique em *capacidade e eficiência*.
+
Por padrão, a guia *capacidade* está selecionada.

. Veja os detalhes da capacidade no nível do cluster e do nó.
+
.. Visualizar a previsão de capacidade no nível do nó.
+
Para sistemas ONTAP, as informações sobre a capacidade RAW estão disponíveis no ClusterViewer.

.. Clique em *Adicionar capacidade* para enviar uma notificação à NetApp ou ao seu parceiro para adicionar capacidade.


. Veja a eficiência de storage e a economia de dados do seu sistema de storage.
+
.. Se a taxa de eficiência de storage do seu sistema de storage for superior à taxa média de eficiência de storage, clique em *compartilhar sua história de sucesso* para nos informar sobre as práticas recomendadas seguidas.
.. Se a taxa de eficiência de storage do seu sistema de storage for inferior à taxa média de eficiência de storage, clique em *Fale conosco* para nos informar sobre as configurações do seu sistema de storage.




Para obter mais informações sobre capacidade e eficiência de storage, link:reference_aiq_faq.html["Perguntas frequentes sobre o Digital Advisor"]consulte .
