---
sidebar: sidebar 
permalink: task_identify_capacity_system.html 
keywords: capacity, space, increase, ontap systems, storagegrid, storage expansion 
summary: Fornece informações para aumentar a capacidade do sistema. 
---
= Identifique sistemas de armazenamento próximos do limite de capacidade no Digital Advisor.
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Identifique sistemas que estejam atingindo limites de capacidade proativamente e envie uma solicitação para aumentar a capacidade do seu sistema de storage.

No ONTAP, você pode visualizar sistemas que excederam 90% da capacidade ou excederam 90% da capacidade em 1, 3 e 6 meses. No StorageGRID, você pode visualizar sistemas que excederam 70% da capacidade ou excederam 70% da capacidade em 1, 3 e 6 meses.

.Passos
. No widget *Planejamento*, selecione *expansão de storage*.
+
Por padrão, os sistemas ONTAP que excederam 90% de capacidade ou estão próximos a 90% de capacidade são exibidos.

. Selecione a guia *StorageGRID* para visualizar os sistemas StorageGRID que excederam 70% da capacidade ou estão próximos de atingir 70% da capacidade.
. Selecione os sistemas para os quais deseja aumentar a capacidade.
. Selecione *Ver Previsão de Capacidade* para visualizar a previsão de capacidade para os próximos 6 meses.
. Selecione *Solicitar para adicionar capacidade*.
. Opcionalmente, forneça quaisquer comentários.
. Selecione *Enviar* para enviar a solicitação à equipe de storage da NetApp para auxiliar na expansão de storage dos sistemas selecionados.

