---
sidebar: sidebar 
permalink: task_compare_config_drift_template.html 
keywords: config deviation, drift, configuration, compare template 
summary: Fornece informações para comparar um modelo de desvio de configuração. 
---
= Compare os modelos de desvio de configuração no Digital Advisor.
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode comparar as configurações do sistema e do cluster e detetar os desvios de configuração em tempo quase real.

.Passos
. No painel esquerdo, clique em *Config Drift*.
. Selecione um dos modelos existentes ou clique em *Adicionar modelo* para adicionar um novo modelo.
. Gerar um relatório de desvio de configuração
+
Você pode gerar um relatório imediatamente ou agendar o relatório para ser gerado semanalmente ou mensalmente.



[cols="50,50"]
|===
| Para gerar um relatório imediatamente | Para programar o relatório a ser gerado semanalmente ou mensalmente 


 a| 
. Selecione uma categoria e forneça os valores solicitados para o relatório.
. Selecione a opção *include only Drifts* (incluir apenas desvios) para transferir apenas as alterações de desvio de configuração.
. Clique em *Enviar*.
. link:task_generate_reports.html["Baixe e veja o relatório de deriva de configuração"].
. Execute o Ansible Playbook (incluído como parte do relatório de desvio de configuração) para mitigar as desvios.

 a| 
. Clique na guia *Relatório de Agendamento*.
. Selecione uma categoria e forneça os valores solicitados para o relatório.
. Selecione a opção *include only Drifts* (incluir apenas desvios) para transferir apenas as alterações de desvio de configuração.
. Selecione a frequência do relatório.
. Selecione a data de início e a data de fim para o relatório.
. Clique em *Enviar*.
. link:task_generate_reports.html["Baixe e veja o relatório de deriva de configuração"].
. Execute o Ansible Playbook (incluído como parte do relatório de desvio de configuração) para mitigar as desvios.


|===
É enviado um e-mail com os detalhes do desvio de configuração entre os sistemas selecionados.
