---
sidebar: sidebar 
permalink: task-integrating-with-cloud-insights-to-view-vm-details.html 
keywords: Cloud Insights, VMs, virtual machines, Data Infrastructure Insights 
summary: Fornece informações sobre as máquinas virtuais no Data Infrastructure Insights 
---
= Utilize o Digital Advisor para visualizar os dados de máquinas virtuais disponíveis no Data Infrastructure Insights.
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O Digital Advisor agora está integrado à versão básica do Data Infrastructure Insights para fornecer um inventário de pilha completa e verificações de interoperabilidade aos clientes.

Os benefícios dessa integração são:

* Monitoramento SaaS simplificado do ONTAP
* Visibilidade do monitoramento full-stack da VMware
* Economia de produtividade para os clientes por meio de verificações automatizadas de interoperabilidade para ajudar no Planejamento de atualização do ONTAP. Isso resulta em atualizações mais suaves do ONTAP e reduz os riscos de incompatibilidade com os hosts.



NOTE: Esse recurso está disponível somente para contratos de atualização do SupportEdge Advisor, do SupportEdge Expert e do consultor digital.

.Passos
. No widget *Inventário*, clique em *Máquinas Virtuais* para visualizar os dados disponíveis no Data Infrastructure Insights.
. Clique na guia *Visão geral da máquina virtual*.
. Clique em *Count of ESX hosts* (contagem de hosts ESX*) para exibir informações sobre o host.
. Clique no *Nome ESX* para navegar até o Data Infrastructure Insights e ver mais informações.

