---
sidebar: sidebar 
permalink: view-firmware-update-recommendations.html 
keywords: Upgrade Advisor, firmware recommendations, storage firmware, SP/BMC firmware, system files, security files 
summary: Veja recomendações de atualização de firmware de armazenamento, firmware SP/BMC, arquivos de sistema e arquivos de segurança. 
---
= Veja as recomendações de atualização de firmware no Digital Advisor.
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Agora, os clientes podem economizar tempo e esforço, permitindo que a Control Tower atualize automaticamente seus sistemas com as versões de firmware mais recentes, eliminando a necessidade de intervenção manual ou agendamento. Esta atualização reduz o risco de encontrar problemas devido a versões de firmware desatualizadas ou incompatíveis, garantindo o desempenho, estabilidade e segurança do sistema ideais.

Os clientes receberão notificações e alertas oportunos sobre o status das atualizações de firmware, com opções para ativar as configurações de AutoSupport e atualização automática.

.Passos
. Na página do painel, clique em *outras recomendações* no widget *Upgrade Advisor*.
. Clique em *Ver recomendações* para ver a lista de recomendações.
. Na coluna *Update Status*, clique em *See Progress* para exibir os clusters que são elegíveis para uma atualização.
. Em caso de problemas, clique nos respetivos links para visualizar as etapas para mitigar os problemas.

