= Suporte a interruptores autorizados
:allow-uri-read: 




=== Suporte a interruptores autorizados

Agora você pode visualizar informações sobre os switches SAN Fibre Channel Brocade que têm direito a suporte. Isso inclui detalhes sobre o modelo do switch, número de série e status de suporte. link:https://docs.netapp.com/us-en/active-iq/task_view_inventory_details.html["Aprenda como visualizar o suporte intitulado switches"] .



=== Limite para dados de AutoSupport RSS

O limite de Envios Interrompidos Recentemente (RSS), no widget AutoSupport , foi estendido de 48 horas (2 dias) para 216 horas (9 dias) antes que um sistema seja sinalizado como RSS.  Isso é feito para acomodar plataformas como o StorageGRID , que enviam apenas dados semanais do AutoSupport .



=== Seção de API obsoleta no catálogo de API do Digital Advisor

Uma nova seção de API obsoleta está disponível no catálogo de API do Digital Advisor .  Ele lista as APIs que estão programadas para descontinuação, juntamente com cronogramas de descontinuação e APIs alternativas.



=== Previsão de capacidade V2 e descontinuação dos módulos da API End of Support

Os módulos de previsão de capacidade V2 e API de fim de suporte estão programados para descontinuação.  Para acessar as APIs obsoletas ou saber sobre os cronogramas de obsolescência e APIs alternativas, navegue até *Serviços de API -> Procurar -> APIs obsoletas*.
